org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47.4.10,)
loader_version_range=[47,)

mod_id=fastmove
mod_name=FastMove [Forge Port]
mod_license=CC BY-SA 4.0
mod_version=1.0.0
mod_group_id=io.github.beeebea
archives_base_name=FastMove-Forge

player_anim=1.0.2-rc1+1.20
